"""Writes css/shapes.css: Material 3 Expressive shapes as clip-path polygons.

Every polygon has the same number of points, starting at the top and running
clockwise, so the browser can morph any shape into any other with a transition.
Run from the repo root:  python3 tools/build_shapes_css.py
"""
import os, sys, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from shapes import SHAPES, polar

N = 144
def fmt(v):
    s = f"{v:.1f}".rstrip('0').rstrip('.')
    return s if s not in ('-0', '') else '0'

lines = ["/* Generated by tools/build_shapes_css.py. Material 3 Expressive shape library,",
         "   drawn as clip-path polygons that share one point count so they can morph. */",
         ":root {"]
for name, pts in SHAPES.items():
    pol = polar(pts, N)
    coords = ",".join(f"{fmt(50 + 50 * r * math.sin(a))}% {fmt(50 - 50 * r * math.cos(a))}%" for a, r in pol)
    lines.append(f"  --shape-{name}: polygon({coords});")
lines.append("}")
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(root, 'css', 'shapes.css')
open(out, 'w').write("\n".join(lines) + "\n")
print(out, os.path.getsize(out), 'bytes')
